# Steps In Machine Learning Algorithms
* Import Packages
* Load The input
* Basic Checks and EDA
* Train-Test-Split
* Defining the model
* Training- fit()
* Prediction- predict()
* Evaluation

In [2]:
# Import Packages
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [3]:
#Load the input
data = pd.read_csv('hp_data.csv')
data.head()

,place,built,sqft,sale,yearsOld,floor,totalFloor,bhk,price
0,BTM Layout,Super built-up Area,1450,Resale,5,1,4,1,6300000
1,Yelahanka,Super built-up Area,2190,Resale,5,3,5,3,11500000
2,Whitefield,Super built-up Area,1019,Resale,1,2,5,2,3800000
3,Ambalipura,Super built-up Area,1857,Resale,15,4,5,4,10500000
4,Yelahanka,Super built-up Area,2190,Resale,5,3,5,3,11500000

In [4]:
#Basic Checks and EDA
data.shape

(3500, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   place       3500 non-null   object
 1   built       3500 non-null   object
 2   sqft        3500 non-null   int64
 3   sale        3500 non-null   object
 4   yearsOld    3500 non-null   int64
 5   floor       3500 non-null   int64
 6   totalFloor  3500 non-null   int64
 7   bhk         3500 non-null   int64
 8   price       3500 non-null   int64
dtypes: int64(6), object(3)
memory usage: 246.2+ KB

In [6]:
data.corr()

                sqft  yearsOld     floor  totalFloor       bhk     price
sqft        1.000000  0.229461  0.356053    0.358946  0.356053  0.778364
yearsOld    0.229461  1.000000 -0.116427   -0.142562 -0.116427  0.215712
floor       0.356053 -0.116427  1.000000    0.958100  1.000000  0.263472
totalFloor  0.358946 -0.142562  0.958100    1.000000  0.958100  0.402256
bhk         0.356053 -0.116427  1.000000    0.958100  1.000000  0.263472
price       0.778364  0.215712  0.263472    0.402256  0.263472  1.000000

In [7]:
data.describe()

,sqft,yearsOld,floor,totalFloor,bhk,price
count,3500.000000,3500.000000,3500.000000,3500.000000,3500.000000,3.500000e+03
mean,1538.163143,7.602000,4.197714,6.371429,4.197714,8.067807e+06
std,416.264178,3.803196,4.782410,4.461808,4.782410,4.984973e+06
min,1019.000000,1.000000,1.000000,4.000000,1.000000,3.800000e+06
25%,1200.000000,5.000000,1.000000,4.000000,1.000000,4.800000e+06
50%,1543.000000,5.000000,3.000000,4.000000,3.000000,6.600000e+06
75%,1784.000000,10.000000,4.000000,5.000000,4.000000,1.050000e+07
max,4856.000000,15.000000,18.000000,29.000000,18.000000,4.750000e+07

In [8]:
data.isnull().sum()

place         0
built         0
sqft          0
sale          0
yearsOld      0
floor         0
totalFloor    0
bhk           0
price         0
dtype: int64

In [9]:
#Define X and Y
X = data.loc[:,['sqft','totalFloor','bhk']]
y = data.price

In [10]:
X

      sqft  totalFloor  bhk
0     1450           4    1
1     2190           5    3
2     1019           5    2
3     1857           5    4
4     2190           5    3
...    ...         ...  ...
3495  1019           5    2
3496  1450           4    1
3497  1330           4    1
3498  1200           4    1
3499  1019           5    2

[3500 rows x 3 columns]

In [11]:
#Train-Test-split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [12]:
#Define model
 
model = LinearRegression()

In [13]:
model

LinearRegression()

In [14]:
X_train

      sqft  totalFloor  bhk
796   1200           4    1
754   2190           5    3
184   1200           4    1
520   2190           5    3
281   1857           5    4
...    ...         ...  ...
955   2190           5    3
2703  1019           5    2
203   1330           4    1
2373  1330           4    1
2897  1450           4    1

[2625 rows x 3 columns]

In [16]:
y_train

796      4800000
754     11500000
184      4800000
520     11500000
281     10500000
          ...
955     11500000
2703     3800000
203      7350000
2373     7350000
2897     6300000
Name: price, Length: 2625, dtype: int64

In [15]:
X_test

      sqft  totalFloor  bhk
254   1100           4    3
3180  2190           5    3
3137  1019           5    2
1612  1330           4    1
1294  1543           4    3
...    ...         ...  ...
954   1330           4    1
155   1330           4    1
3016  1330           4    1
1237  1200           4    1
996   1672          10    6

[875 rows x 3 columns]

In [17]:
#TRain the model
model.fit(X_train,y_train)

LinearRegression()

In [18]:
# prediction
price_predict = model.predict(X_test) # input of testing data
price_predict

array([ 1753204.45159851, 13413862.55139982,  4512565.16783565,
        7122788.95488186,  5744369.07710099,  8203917.07014213,
        8203917.07014213, 13002914.69457738,  8950722.33077772,
        5951566.83001657,  5744369.07710099,  7122788.95488186,
        5744369.07710099,  8950722.33077772,  4512565.16783565,
       13002914.69457738,  8203917.07014213, 13002914.69457738,
        5951566.83001657,  5744369.07710099,  5744369.07710099,
        8950722.33077772,  5744369.07710099,  5744369.07710099,
        5744369.07710099,  5951566.83001657, 13413862.55139982,
       13002914.69457738,  4512565.16783565,  5744369.07710099,
        8950722.33077772, 13002914.69457738,  5951566.83001657,
        4512565.16783565,  1753204.45159851, 13413862.55139982,
        5744369.07710099,  4512565.16783565,  4512565.16783565,
       13413862.55139982,  4512565.16783565,  8950722.33077772,
        4512565.16783565,  4512565.16783565,  4512565.16783565,
        5744369.07710099, 13002914.69457738,  8765020.89036866,
        8765020.89036866, 13002914.69457738,  8203917.07014213,
        8203917.07014213,  8950722.33077772,  8950722.33077772,
        5744369.07710099, 13002914.69457738,  8950722.33077772,
       13413862.55139982,  8950722.33077772,  5951566.83001657,
        8950722.33077772,  8765020.89036866,  8950722.33077772,
        4512565.16783565,  7122788.95488186,  7122788.95488186,
       13002914.69457738,  8765020.89036866,  8950722.33077772,
        4512565.16783565, 13002914.69457738,  8203917.07014213,
        8950722.33077772,  7122788.95488186, 35592514.45924485,
        4512565.16783565,  8203917.07014213,  4512565.16783565,
        8765020.89036866,  5951566.83001657,  1753204.45159851,
        5951566.83001657, 13413862.55139982,  4512565.16783565,
        8765020.89036866, 17855487.99033944, 13002914.69457738,
        4512565.16783565, 13002914.69457738,  4512565.16783565,
        8950722.33077772,  8950722.33077772,  5951566.83001657,
        7122788.95488186,  5744369.07710099,  1753204.45159851,
        7122788.95488186,  1753204.45159851, 13413862.55139982,
        5951566.83001657,  8950722.33077772, 13002914.69457738,
        7122788.95488186, 13413862.55139982,  5744369.07710099,
        5744369.07710099,  4512565.16783565,  4512565.16783565,
       13413862.55139982,  5951566.83001657,  8950722.33077772,
        5951566.83001657,  5744369.07710099,  5744369.07710099,
       13413862.55139982, 13413862.55139982, 13002914.69457738,
        8765020.89036866,  8950722.33077772,  7122788.95488186,
        5744369.07710099,  8203917.07014213,  5951566.83001657,
        5744369.07710099,  8950722.33077772, 13002914.69457738,
       13413862.55139982,  8203917.07014213,  4512565.16783565,
       13002914.69457738,  7122788.95488186,  1753204.45159851,
       13413862.55139982,  5744369.07710099,  1753204.45159851,
        1753204.45159851, 13413862.55139982,  8203917.07014213,
        8765020.89036866,  8950722.33077772, 13002914.69457738,
        8950722.33077772, 13002914.69457738,  8765020.89036866,
        7122788.95488186,  8950722.33077772,  8203917.07014213,
        8203917.07014213,  4512565.16783565,  8950722.33077772,
        1753204.45159851,  4512565.16783565, 13002914.69457738,
       13002914.69457738,  5951566.83001657, 13002914.69457738,
       13413862.55139982,  4512565.16783565,  8203917.07014213,
        8765020.89036866,  5951566.83001657,  8203917.07014213,
        8950722.33077772, 13413862.55139982, 13002914.69457738,
        8765020.89036866,  4512565.16783565,  7122788.95488186,
        1753204.45159851, 13413862.55139982,  8203917.07014213,
        1753204.45159851,  5744369.07710099,  8950722.33077772,
        7122788.95488186,  7122788.95488186,  5951566.83001657,
        1753204.45159851, 13413862.55139982, 13002914.69457738,
        5744369.07710099, 13413862.55139982, 13002914.69457738,
       17855487.99033944,  7122788.95488186,  1753204.45159851,
        8950722.33077772, 13002914.69457738, 13002914.69457738,
        8203917.07014213,  8203917.07014213, 13413862.55139982,
        7122788.95488186,  5744369.07710099,  8950722.33077772,
        5744369.07710099, 13413862.55139982,  5744369.07710099,
        8765020.89036866,  1753204.45159851,  8950722.33077772,
        7122788.95488186,  5951566.83001657, 13002914.69457738,
        4512565.16783565,  8203917.07014213,  5951566.83001657,
        5951566.83001657, 13002914.69457738, 13002914.69457738,
        5744369.07710099,  5744369.07710099,  4512565.16783565,
       13413862.55139982,  1753204.45159851,  1753204.45159851,
        8950722.33077772, 13002914.69457738,  1753204.45159851,
        4512565.16783565,  5744369.07710099,  8950722.33077772,
        7122788.95488186, 13002914.69457738,  1753204.45159851,
       13413862.55139982,  5744369.07710099, 13413862.55139982,
        1753204.45159851,  5744369.07710099,  7122788.95488186,
        8950722.33077772, 13002914.69457738,  5744369.07710099,
        8765020.89036866,  7122788.95488186, 13002914.69457738,
        5951566.83001657,  8950722.33077772,  4512565.16783565,
       13413862.55139982,  8765020.89036866,  8203917.07014213,
       13413862.55139982,  1753204.45159851,  1753204.45159851,
       13002914.69457738,  5744369.07710099, 13002914.69457738,
        7122788.95488186, 13002914.69457738, 13413862.55139982,
        8765020.89036866, 13002914.69457738, 13413862.55139982,
       13413862.55139982, 13002914.69457738, 13413862.55139982,
        5744369.07710099, 13002914.69457738,  8203917.07014213,
        8765020.89036866,  8950722.33077772,  7122788.95488186,
        8765020.89036866,  5744369.07710099,  5744369.07710099,
        5744369.07710099, 13002914.69457738,  5744369.07710099,
       13413862.55139982,  5951566.83001657,  8203917.07014213,
        5951566.83001657,  5951566.83001657,  8950722.33077772,
       29324407.082306  ,  8765020.89036866,  8203917.07014213,
        4512565.16783565,  5951566.83001657,  1753204.45159851,
        8765020.89036866,  4512565.16783565,  5951566.83001657,
        7122788.95488186,  5951566.83001657,  4512565.16783565,
        8950722.33077772,  8950722.33077772,  1753204.45159851,
        1753204.45159851,  8203917.07014213, 13413862.55139982,
        4512565.16783565,  7122788.95488186,  8950722.33077772,
        8950722.33077772,  8203917.07014213,  5951566.83001657,
        5744369.07710099, 13413862.55139982,  8203917.07014213,
        5744369.07710099,  5744369.07710099,  1753204.45159851,
        8950722.33077772,  5951566.83001657, 13002914.69457738,
        8203917.07014213,  5744369.07710099,  5951566.83001657,
        8203917.07014213,  8765020.89036866, 13002914.69457738,
        5744369.07710099,  1753204.45159851,  8203917.07014213,
        8950722.33077772,  4512565.16783565, 13002914.69457738,
        5951566.83001657,  1753204.45159851,  4512565.16783565,
        5744369.07710099,  5744369.07710099,  1753204.45159851,
        5744369.07710099,  7122788.95488186,  8765020.89036866,
        1753204.45159851, 13413862.55139982,  8203917.07014213,
        4512565.16783565,  7122788.95488186,  5744369.07710099,
        8203917.07014213, 13413862.55139982,  5744369.07710099,
        8203917.07014213,  5744369.07710099, 13413862.55139982,
        5744369.07710099,  8765020.89036866, 13002914.69457738,
        8203917.07014213, 13002914.69457738, 29324407.082306  ,
        8950722.33077772,  5951566.83001657,  5744369.07710099,
        8950722.33077772, 13413862.55139982,  8203917.07014213,
       13413862.55139982,  5744369.07710099, 13413862.55139982,
        1753204.45159851, 13002914.69457738,  4512565.16783565,
        8203917.07014213,  8765020.89036866, 13002914.69457738,
        1753204.45159851, 13002914.69457738,  4512565.16783565,
        8950722.33077772,  8950722.33077772,  1753204.45159851,
        5744369.07710099,  1753204.45159851, 35592514.45924485,
        8765020.89036866, 13413862.55139982,  8203917.07014213,
        1753204.45159851,  4512565.16783565,  5744369.07710099,
        7122788.95488186, 13002914.69457738,  1753204.45159851,
        7122788.95488186, 13413862.55139982, 13002914.69457738,
       13002914.69457738,  7122788.95488186, 13413862.55139982,
        8765020.89036866,  7122788.95488186,  8950722.33077772,
        1753204.45159851,  7122788.95488186, 13413862.55139982,
        1753204.45159851,  8203917.07014213,  7357033.37985492,
        1753204.45159851,  8203917.07014213,  7122788.95488186,
        7122788.95488186, 13413862.55139982,  5744369.07710099,
        4512565.16783565,  4512565.16783565,  4512565.16783565,
        5744369.07710099,  5744369.07710099,  8765020.89036866,
        8950722.33077772,  1753204.45159851,  8950722.33077772,
        5951566.83001657,  5951566.83001657,  1753204.45159851,
        8950722.33077772,  8203917.07014213, 13002914.69457738,
        8203917.07014213,  1753204.45159851,  8765020.89036866,
        8765020.89036866,  8950722.33077772,  7122788.95488186,
        4512565.16783565,  5951566.83001657,  8203917.07014213,
        5951566.83001657,  5951566.83001657,  5951566.83001657,
        5744369.07710099,  5951566.83001657,  7122788.95488186,
        1753204.45159851,  8765020.89036866,  8203917.07014213,
        5744369.07710099,  5951566.83001657,  1753204.45159851,
       13002914.69457738,  4512565.16783565,  1753204.45159851,
        1753204.45159851,  8950722.33077772,  1753204.45159851,
       13002914.69457738, 13002914.69457738,  5951566.83001657,
        4512565.16783565,  8950722.33077772,  1753204.45159851,
       13413862.55139982, 13413862.55139982,  5951566.83001657,
        5951566.83001657,  8950722.33077772,  5951566.83001657,
        4512565.16783565,  5951566.83001657, 13413862.55139982,
        1753204.45159851,  8950722.33077772,  7122788.95488186,
        1753204.45159851,  8203917.07014213, 13413862.55139982,
       13002914.69457738, 13413862.55139982,  7122788.95488186,
        8765020.89036866,  4512565.16783565, 13413862.55139982,
        8203917.07014213,  8203917.07014213,  8950722.33077772,
        8765020.89036866, 13002914.69457738,  8203917.07014213,
        5951566.83001657,  5951566.83001657, 13002914.69457738,
        1753204.45159851, 13413862.55139982,  5744369.07710099,
        5744369.07710099,  4512565.16783565, 13002914.69457738,
       13002914.69457738,  8765020.89036866,  8950722.33077772,
       13002914.69457738, 13002914.69457738,  8203917.07014213,
        7122788.95488186, 13413862.55139982,  8950722.33077772,
        4512565.16783565,  4512565.16783565,  5744369.07710099,
        5951566.83001657,  8203917.07014213, 13413862.55139982,
        8765020.89036866,  8950722.33077772,  8765020.89036866,
        1753204.45159851,  8765020.89036866,  8765020.89036866,
        4512565.16783565,  8203917.07014213,  4512565.16783565,
        5951566.83001657,  8950722.33077772,  1753204.45159851,
        4512565.16783565,  5744369.07710099,  8765020.89036866,
       13413862.55139982, 13413862.55139982,  5951566.83001657,
        1753204.45159851,  8203917.07014213,  8950722.33077772,
       13002914.69457738,  4512565.16783565,  4512565.16783565,
       13413862.55139982, 13413862.55139982,  5951566.83001657,
        5744369.07710099, 29324407.082306  , 13413862.55139982,
        8950722.33077772,  1753204.45159851,  4512565.16783565,
       13413862.55139982,  8765020.89036866,  4512565.16783565,
        5951566.83001657,  1753204.45159851,  8950722.33077772,
        4512565.16783565,  5744369.07710099,  7122788.95488186,
        8765020.89036866, 13002914.69457738,  4512565.16783565,
        5951566.83001657, 13413862.55139982,  8765020.89036866,
        4512565.16783565,  1753204.45159851,  8950722.33077772,
        8950722.33077772,  5744369.07710099,  1753204.45159851,
        5951566.83001657,  4512565.16783565, 13002914.69457738,
        8203917.07014213,  1753204.45159851,  8950722.33077772,
       13002914.69457738, 13413862.55139982, 13413862.55139982,
       13413862.55139982, 13002914.69457738,  8203917.07014213,
       13002914.69457738, 13413862.55139982,  8203917.07014213,
        8950722.33077772,  8203917.07014213,  4512565.16783565,
        7122788.95488186, 13413862.55139982,  8203917.07014213,
        8203917.07014213,  5744369.07710099,  5951566.83001657,
        4512565.16783565,  8203917.07014213,  8203917.07014213,
        8765020.89036866,  8203917.07014213, 13413862.55139982,
        5744369.07710099,  8765020.89036866,  7122788.95488186,
        5744369.07710099,  8765020.89036866,  4512565.16783565,
        8765020.89036866,  8203917.07014213,  8203917.07014213,
        5744369.07710099,  1753204.45159851,  1753204.45159851,
        8203917.07014213,  7122788.95488186,  5744369.07710099,
        8203917.07014213, 13002914.69457738, 13413862.55139982,
        8950722.33077772,  5744369.07710099, 13002914.69457738,
        5744369.07710099,  8765020.89036866,  8765020.89036866,
        4512565.16783565,  8950722.33077772,  1753204.45159851,
        5744369.07710099,  1753204.45159851, 17855487.99033944,
        5744369.07710099,  5951566.83001657, 13413862.55139982,
        7122788.95488186,  8950722.33077772,  8203917.07014213,
        5951566.83001657,  5951566.83001657,  4512565.16783565,
       13413862.55139982, 13413862.55139982,  8203917.07014213,
       13413862.55139982,  5951566.83001657,  5744369.07710099,
       35592514.45924485,  8950722.33077772,  4512565.16783565,
        8765020.89036866,  7122788.95488186,  8203917.07014213,
        8203917.07014213,  7122788.95488186, 13002914.69457738,
        7122788.95488186, 13413862.55139982,  4512565.16783565,
        8203917.07014213, 46538331.52654937,  8950722.33077772,
        7122788.95488186,  5951566.83001657,  1753204.45159851,
        7122788.95488186,  5744369.07710099,  8765020.89036866,
       13413862.55139982,  7122788.95488186,  7122788.95488186,
       13002914.69457738,  4512565.16783565,  8765020.89036866,
       13002914.69457738, 13413862.55139982, 13413862.55139982,
        8950722.33077772, 13413862.55139982, 13413862.55139982,
        5951566.83001657,  8765020.89036866,  5744369.07710099,
        8203917.07014213, 13002914.69457738,  5744369.07710099,
       13413862.55139982,  8203917.07014213,  8203917.07014213,
        7122788.95488186,  8203917.07014213,  8203917.07014213,
        7122788.95488186, 13413862.55139982, 13002914.69457738,
        5744369.07710099, 13002914.69457738,  5951566.83001657,
       13413862.55139982, 13002914.69457738,  8765020.89036866,
        7122788.95488186,  8950722.33077772,  1753204.45159851,
        5951566.83001657,  8950722.33077772,  8765020.89036866,
        1753204.45159851,  5951566.83001657,  7122788.95488186,
        5744369.07710099,  8950722.33077772,  8203917.07014213,
        4512565.16783565,  7122788.95488186,  8203917.07014213,
        1753204.45159851, 13002914.69457738,  7122788.95488186,
        1753204.45159851,  8765020.89036866,  7122788.95488186,
        8765020.89036866,  1753204.45159851,  5951566.83001657,
        8950722.33077772, 13413862.55139982,  5951566.83001657,
        8203917.07014213,  8765020.89036866,  8950722.33077772,
       13002914.69457738,  5951566.83001657,  7122788.95488186,
        8950722.33077772,  8765020.89036866,  4512565.16783565,
        1753204.45159851,  1753204.45159851,  8950722.33077772,
        5744369.07710099, 13002914.69457738, 46538331.52654937,
        4512565.16783565,  8765020.89036866,  5951566.83001657,
       13413862.55139982, 13413862.55139982,  1753204.45159851,
        5951566.83001657, 46538331.52654937,  4512565.16783565,
        5951566.83001657,  1753204.45159851,  7122788.95488186,
       13002914.69457738,  7122788.95488186,  7122788.95488186,
        4512565.16783565,  1753204.45159851,  5951566.83001657,
        5744369.07710099,  8765020.89036866,  1753204.45159851,
        7122788.95488186,  8950722.33077772,  7122788.95488186,
        7122788.95488186,  8950722.33077772,  8950722.33077772,
        5951566.83001657, 13413862.55139982,  5951566.83001657,
       13002914.69457738,  1753204.45159851,  8950722.33077772,
        8203917.07014213, 13002914.69457738,  8765020.89036866,
        5744369.07710099,  5744369.07710099,  1753204.45159851,
        1753204.45159851,  8765020.89036866,  7122788.95488186,
        5951566.83001657,  8203917.07014213,  8765020.89036866,
        5744369.07710099, 13002914.69457738,  4512565.16783565,
        8765020.89036866, 13002914.69457738,  7122788.95488186,
        1753204.45159851, 13002914.69457738,  8203917.07014213,
        7122788.95488186,  1753204.45159851,  8765020.89036866,
        5951566.83001657,  8950722.33077772,  5951566.83001657,
        8203917.07014213,  1753204.45159851,  5951566.83001657,
        8203917.07014213, 13002914.69457738,  8203917.07014213,
        4512565.16783565,  7357033.37985492,  5951566.83001657,
       13002914.69457738,  4512565.16783565,  5744369.07710099,
        4512565.16783565, 13413862.55139982,  7122788.95488186,
       13413862.55139982,  8203917.07014213,  7122788.95488186,
        1753204.45159851,  8950722.33077772,  7122788.95488186,
        5951566.83001657,  8765020.89036866,  5951566.83001657,
        5744369.07710099, 13413862.55139982,  1753204.45159851,
        5951566.83001657,  4512565.16783565,  8203917.07014213,
       13413862.55139982,  5951566.83001657,  7122788.95488186,
        7122788.95488186,  5744369.07710099,  8950722.33077772,
        7122788.95488186,  5744369.07710099,  8203917.07014213,
        5744369.07710099,  4512565.16783565, 13002914.69457738,
        7122788.95488186,  8950722.33077772,  4512565.16783565,
       13413862.55139982, 13413862.55139982, 17855487.99033944,
        5951566.83001657, 13413862.55139982,  5744369.07710099,
        8765020.89036866,  8950722.33077772,  5951566.83001657,
        5951566.83001657,  5951566.83001657,  8950722.33077772,
       13002914.69457738, 13002914.69457738,  7122788.95488186,
        1753204.45159851, 13002914.69457738, 35592514.45924485,
        7122788.95488186,  7122788.95488186,  1753204.45159851,
       13413862.55139982,  4512565.16783565,  8765020.89036866,
        1753204.45159851,  5951566.83001657,  1753204.45159851,
       13002914.69457738,  1753204.45159851,  8203917.07014213,
        8203917.07014213,  5744369.07710099,  8765020.89036866,
        8203917.07014213,  7122788.95488186,  4512565.16783565,
        1753204.45159851,  4512565.16783565,  5744369.07710099,
        7122788.95488186,  7122788.95488186,  7122788.95488186,
        5951566.83001657, 13002914.69457738])

In [19]:
y_test

254      4900000
3180    11500000
3137     3800000
1612     7350000
1294     4025000
          ...
954      7350000
155      7350000
3016     7350000
1237     4800000
996     15000000
Name: price, Length: 875, dtype: int64

In [20]:
#Evaluation
r2_score(y_test,price_predict)

0.8485633350439393